export const CREATE_TWEET_REQUEST = "CREATE_TWEET_REQUEST";
export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS";
export const CREATE_TWEET_FAILURE = "CREATE_TWEET_FAILURE";

export const DELETE_TWEET_REQUEST = "DELETE_TWEET_REQUEST";
export const DELETE_TWEET_SUCCESS = "DELETE_TWEET_SUCCESS";
export const DELETE_TWEET_FAILURE = "DELETE_TWEET_FAILURE";

export const GET_ALL_TWEET_REQUEST = "GET_ALL_TWEET_REQUEST";
export const GET_ALL_TWEET_SUCCESS = "GET_ALL_TWEET_SUCCESS";
export const GET_ALL_TWEET_FAILURE = "GET_ALL_TWEET_FAILURE";

export const GET_ALL_USERS_TWEET_REQUEST = "GET_ALL_USERS_TWEET_REQUEST";
export const GET_ALL_USERS_TWEET_SUCCESS = "GET_ALL_USERS_TWEET_SUCCESS";
export const GET_ALL_USERS_TWEET_FAILURE = "GET_ALL_USERS_TWEET_FAILURE";

export const USERS_LIKED_TWEET_REQUEST = "USERS_LIKED_TWEET_REQUEST";
export const USERS_LIKED_TWEET_SUCCESS = "USERS_LIKED_TWEET_SUCCESS";
export const USERS_LIKED_TWEET_FAILURE = "USERS_LIKED_TWEET_FAILURE";

export const USERS_BOOKMARK_TWEET_REQUEST = "USERS_BOOKMARK_TWEET_REQUEST";
export const USERS_BOOKMARK_TWEET_SUCCESS = "USERS_BOOKMARK_TWEET_SUCCESS";
export const USERS_BOOKMARK_TWEET_FAILURE = "USERS_BOOKMARK_TWEET_FAILURE";

export const LIKE_TWEET_REQUEST = "LIKE_TWEET_REQUEST";
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAILURE = "LIKE_TWEET_FAILURE";

export const BOOKMARK_TWEET_REQUEST = "BOOKMARK_TWEET_REQUEST";
export const BOOKMARK_TWEET_SUCCESS = "BOOKMARK_TWEET_SUCCESS";
export const BOOKMARK_TWEET_FAILURE = "BOOKMARK_TWEET_FAILURE";

export const FIND_TWEET_BY_ID_REQUEST = "FIND_TWEET_BY_ID_REQUEST";
export const FIND_TWEET_BY_ID_SUCCESS = "FIND_TWEET_BY_ID_SUCCESS";
export const FIND_TWEET_BY_ID_FAILURE = "FIND_TWEET_BY_ID_FAILURE";

export const REPLAY_TWEET_REQUEST = "REPLAY_TWEET_REQUEST";
export const REPLAY_TWEET_SUCCESS = "REPLAY_TWEET_SUCCESS";
export const REPLAY_TWEET_FAILURE = "REPLAY_TWEET_FAILURE";


export const CREATE_RETWEET_REQUEST = "CREATE_RETWEET_REQUEST";
export const CREATE_RETWEET_SUCCESS = "CREATE_RETWEET_SUCCESS";
export const CREATE_RETWEET_FAILURE = "CREATE_RETWEET_FAILURE";
